version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=bobby
      - POSTGRES_PASSWORD=bobby1986
      - POSTGRES_DB=bobbe_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
